### ISSUE TITLE
Locale 'null' and can't get translation value inside appBar

### ISSUE THREAD

**Issue by HoussemTN** [aissat/easy_localization#103]
Hello, Great Package ! 
Translation works well.but when i've added a translation key in my appBar the app crashes.
The Locale return : null
Version : 2.0.2
- I'm using a virtuel device / Android / API 28
- 'company_name' exists in both files (fr,en)
- I can see the translated value by removing the appBar ,start the app,add the appBar , HotReload.
To reproduce this error : 
````
main() {
  runApp(EasyLocalization(
    child: MyApp(),
    path: 'i18n/locales',
    saveLocale: false,
    useOnlyLangCode: true,
    //  fallbackLocale: Locale(Intl.systemLocale),
    supportedLocales: [
      Locale('en'),
      Locale('fr'),
    ],
  ));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    log( EasyLocalization.of(context).locale.toString(), name: this.toString()+"# locale" );
    log( Intl.systemLocale.toString().split("_")[0], name: this.toString()+"# Intl.systemLocale" );
    return MaterialApp(
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        EasyLocalization.of(context).delegate,
      ],
      supportedLocales: EasyLocalization.of(context).supportedLocales,
      locale: EasyLocalization.of(context).locale,
      //  locale:  EasyLocalization.of(context).locale= Locale(Intl.systemLocale.toString().split("_")[0]),

      home: Scaffold(
        appBar: AppBar(
          //right here
          title: Text("company_name".tr()),
        ),
        body: Dashboard(),
      ),
    );
  }
}
````
Stacktrace : 
````[MyApp# locale] null
[MyApp# Intl.systemLocale] en
I/flutter ( 8715): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8715): The following NoSuchMethodError was thrown building MyApp(dirty, dependencies:
I/flutter ( 8715): [EasyLocalizationProvider]):
I/flutter ( 8715): The method 'get' was called on null.
I/flutter ( 8715): Receiver: null
I/flutter ( 8715): Tried calling: get("company_name")
I/flutter ( 8715): 
I/flutter ( 8715): The relevant error-causing widget was:
I/flutter ( 8715):   MyApp file:///C:/Users/Houssem/AndroidStudioProjects/day_experience/lib/main.dart:13:12
I/flutter ( 8715): 
I/flutter ( 8715): When the exception was thrown, this was the stack:
I/flutter ( 8715): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 8715): #1      Localization._resolve (package:easy_localization/src/localization.dart:99:48)
I/flutter ( 8715): #2      Localization.tr (package:easy_localization/src/localization.dart:57:35)
I/flutter ( 8715): #3      tr (package:easy_localization/src/public.dart:8:31)
I/flutter ( 8715): #4      StringTranslateExtension.tr (package:easy_localization/src/public_ext.dart:40:7)
I/flutter ( 8715): #5      MyApp.build (package:day_experience/main.dart:51:38)
I/flutter ( 8715): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
I/flutter ( 8715): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter ( 8715): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8715): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8715): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8715): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8715): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8715): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8715): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8715): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8715): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8715): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8715): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8715): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8715): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8715): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8715): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 8715): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8715): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8715): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8715): #26     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter ( 8715): #27     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter ( 8715): #28     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter ( 8715): #29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter ( 8715): #30     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter ( 8715): #31     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter ( 8715): #32     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter ( 8715): #41     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter ( 8715): #42     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter ( 8715): #43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter ( 8715): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter ( 8715): 
I/flutter ( 8715): ════════════════════════════════════════════════════════════════════════════════════════════════════
[MyApp# locale] null
[MyApp# Intl.systemLocale] en

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyApp(dirty, dependencies: [EasyLocalizationProvider]):
The method 'get' was called on null.
Receiver: null
Tried calling: get("company_name")

The relevant error-causing widget was: 
  MyApp file:///C:/Users/Houssem/AndroidStudioProjects/day_experience/lib/main.dart:13:12
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Localization._resolve (package:easy_localization/src/localization.dart:99:48)
#2      Localization.tr (package:easy_localization/src/localization.dart:57:35)
#3      tr (package:easy_localization/src/public.dart:8:31)
#4      StringTranslateExtension.tr (package:easy_localization/src/public_ext.dart:40:7)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
````

**Comment by moritzmorgenroth** [comment]
@HoussemTN thanks for the report! 
@aissat I can create a PR over the weekend to solve the initial null state issue. I did not see that affect coming in my last PR.

**Comment by aissat** [comment]
@moritzmorgenroth @Overman775  is async load
