### ISSUE TITLE
Flutter driver test stays at white screen

### ISSUE THREAD

**Issue by deadsoul44** [aissat/easy_localization#138]
Hello,

I tried integration testing but it stays at white screen and fails after timeout. However, when I tested child widget of EasyLocalization it does not stay at white screen. What am I doing wrong? Any idea?

**Comment by Overman775** [comment]
@deadsoul44 show log & code sample

**Comment by deadsoul44** [comment]
```

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final appDocumentDirectory = await path_provider.getApplicationDocumentsDirectory();
  await Hive.initFlutter(appDocumentDirectory.path);
  await Hive.openBox('favorites');
  await Hive.openBox('settings');

  Routes.createRoutes();

  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en', 'US'), Locale('tr', 'TR')],
      path: 'translation',
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<SettingsStore>(create: (_) => SettingsStore()),
        Provider<AuthStore>(create: (_) => AuthStore()),
        Provider<AdsStore>(create: (_) => AdsStore()),
        Provider<HomeStore>(create: (_) => HomeStore()),
        Provider<EventsStore>(create: (_) => EventsStore()),
      ],
      child: Observer(
        builder: (context) => MaterialApp(
          theme: LightTheme(Provider.of<SettingsStore>(context).color),
          darkTheme: DarkTheme(),
          themeMode:
              Provider.of<SettingsStore>(context).isDarkMode ? ThemeMode.dark : ThemeMode.system,
          localizationsDelegates: [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            EasyLocalization.of(context).delegate,
          ],
          supportedLocales: EasyLocalization.of(context).supportedLocales,
          locale: EasyLocalization.of(context).locale ?? Locale('en', 'US'),
          debugShowCheckedModeBanner: false,
          home: RootPage(),
          onGenerateRoute: Routes.sailor.generator(),
          navigatorKey: Routes.sailor.navigatorKey,
          navigatorObservers: [
            SailorLoggingObserver(),
            Routes.sailor.navigationStackObserver,
          ],
        ),
      ),
    );
  }
}

```

**Comment by deadsoul44** [comment]
```
flutter drive --target=test_driver/app.dart
Using device MYA L41.
Starting application: test_driver/app.dart
Installing build\app\outputs\apk\app.apk...                        55.1s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        50.9s
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        52.6s
I/flutter ( 6610): Observatory listening on 
00:00 +0: App (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at 
E/FlutterFcmService( 6610): Fatal: failed to find callback
VMServiceFlutterDriver: Isolate found with number:
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Waiting for service extension
VMServiceFlutterDriver: Connected to Flutter application.
00:02 +0:  App starts at 0

02:02 +0 -1: App starts at 0 [E]

  TimeoutException after 0:02:00.000000: Test timed out after 2 minutes.

  package:test_api/src/backend/invoker.dart 333:28               Invoker._handleError.<fn>
  dart:async/zone.dart 1180:38                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 331:10               Invoker._handleError
  package:test_api/src/backend/invoker.dart 287:9                Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  package:test_api/src/backend/invoker.dart 286:38               Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1002:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1251:21                                   _rootCreateTimer
  dart:async/zone.dart 1145:19                                   _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 285:34               Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 239:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 170:33              Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:test_api/src/backend/declarer.dart 169:13              Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                  new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1180:38                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                    new Timer
  dart:async/timer.dart 91:9                                     Timer.run
  dart:async/future.dart 174:11                                  new Future
  package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 438:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:stack_trace/src/chain.dart 99:12                       Chain.capture
  package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
  dart:async/future.dart 202:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1180:38                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage


02:02 +0 -1: App (tearDownAll)

02:02 +0 -1:  App starts at 0 [E]

  Bad state: The client closed with pending request "ext.flutter.driver".

  package:json_rpc_2/src/client.dart 70:24                        new Client.withoutJson.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48    StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1180:38                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/future_impl.dart 165:18                              _FutureListener.handleWhenComplete
  dart:async/future_impl.dart 652:39                              Future._propagateToListeners.handleWhenCompleteCallback
  dart:async/future_impl.dart 708:37                              Future._propagateToListeners
  dart:async/future_impl.dart 609:9                               Future._propagateToListeners
  dart:async/future_impl.dart 526:5                               Future._completeWithValue
  dart:async/future_impl.dart 556:7                               Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48    StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 979:7                                      _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                    _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                        _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                       _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                    _CustomZone.registerBinaryCallback
  dart:async/future_impl.dart 806:10                              _registerErrorHandler
  dart:async/future_impl.dart 283:19                              Future.then
  dart:async/future_impl.dart 777:10                              Future.timeout
  package:flutter_driver/src/driver/vmservice_driver.dart 634:18  _warnIfSlow
  package:flutter_driver/src/driver/vmservice_driver.dart 327:24  VMServiceFlutterDriver.sendCommand
  package:flutter_driver/src/driver/driver.dart 194:11            FlutterDriver.waitFor
  test_driver\app_test.dart 35:24                                 main.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26    StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14    StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1192:38                                    _rootRunUnary
  dart:async/zone.dart 1085:19                                    _CustomZone.runUnary
  dart:async/future_impl.dart 141:18                              _FutureListener.handleValue
  dart:async/future_impl.dart 682:45                              Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 711:32                              Future._propagateToListeners
  dart:async/future_impl.dart 391:9                               Future._addListener.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48    StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 979:7                                      _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                    _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                        _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                       _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1109:19                                    _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 79:23                         _asyncThenWrapperHelper
  test_driver\app_test.dart                                       main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 172:27               Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1109:19                                    _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 79:23                         _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart                      Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 246:15                Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 1619:10                                    _runZoned
  dart:async/zone.dart 1539:10                                    runZoned
  package:test_api/src/backend/invoker.dart 243:5                 Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 170:33               Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 1619:10                                    _runZoned
  dart:async/zone.dart 1539:10                                    runZoned
  package:test_api/src/backend/declarer.dart 169:13               Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 400:30                Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                   new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48    StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1180:38                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 979:7                                      _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                    _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15    StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48    StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 1003:23                                    _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                         Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19                       _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1101:19                                    _CustomZone.registerCallback
  dart:async/zone.dart 1018:22                                    _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                     new Timer
  dart:async/timer.dart 91:9                                      Timer.run
  dart:async/future.dart 174:11                                   new Future
  package:test_api/src/backend/invoker.dart 399:21                Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 1619:10                                    _runZoned
  dart:async/zone.dart 1539:10                                    runZoned
  package:test_api/src/backend/invoker.dart 387:9                 Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 438:15                Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 386:7                 Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                       Chain.capture.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 1619:10                                    _runZoned
  dart:async/zone.dart 1539:10                                    runZoned
  package:stack_trace/src/chain.dart 99:12                        Chain.capture
  package:test_api/src/backend/invoker.dart 385:11                Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 197:11   LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 50:37    _LiveTest.run
  dart:async/future.dart 202:37                                   new Future.microtask.<fn>
  dart:async/zone.dart 1180:38                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 979:7                                      _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                    _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1184:13                                    _rootRun
  dart:async/zone.dart 1077:19                                    _CustomZone.run
  dart:async/zone.dart 979:7                                      _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                    _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                        _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                         _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                    _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                       _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                        _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                    _RawReceivePortImpl._handleMessage


  DriverError: Failed to fulfill WaitFor due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1180:38)
  #4      _CustomZone.run (dart:async/zone.dart:1077:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:165:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:652:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:708:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:609:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
  #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #13     _rootRun (dart:async/zone.dart:1184:13)
  #14     _CustomZone.run (dart:async/zone.dart:1077:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
  #19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
  #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
  #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)



  package:flutter_driver/src/driver/vmservice_driver.dart 334:7  VMServiceFlutterDriver.sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                   _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 88:23                        _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                      Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:test_api/src/backend/invoker.dart 243:5                Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 170:33              Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:test_api/src/backend/declarer.dart 169:13              Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                  new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1180:38                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
  dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                    new Timer
  dart:async/timer.dart 91:9                                     Timer.run
  dart:async/future.dart 174:11                                  new Future
  package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 438:15               Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 1619:10                                   _runZoned
  dart:async/zone.dart 1539:10                                   runZoned
  package:stack_trace/src/chain.dart 99:12                       Chain.capture
  package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
  dart:async/future.dart 202:37                                  new Future.microtask.<fn>
  dart:async/zone.dart 1180:38                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1184:13                                   _rootRun
  dart:async/zone.dart 1077:19                                   _CustomZone.run
  dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                      _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage


02:02 +0 -1: Some tests failed.


Unhandled exception:
Dummy exception to set exit code.
Stopping application instance.
Driver tests failed: 255

```

**Comment by deadsoul44** [comment]
I modified the timeout to be 2 minutes. It fails after 2 minutes. But, no white screen with child widget testing.

**Comment by Overman775** [comment]
@deadsoul44 same issue? https://github.com/flutter/flutter/issues/24703

**Comment by deadsoul44** [comment]
I had to combine two workarounds: 

https://github.com/flutter/flutter/issues/24703#issuecomment-531277291
https://github.com/flutter/flutter/issues/41029#issuecomment-544348116

I am following those two issues to have a better solution. 

Thank you.
