### ISSUE TITLE
Build exceptions during widget tests - how to initialize for widget tests?

### ISSUE THREAD

**Issue by acoutts** [aissat/easy_localization#155]
I want to use EasyLocalization during my widget tests to load i18n strings and render them in the golden snapshots.

But, when I wrap my test widget with EasyLocalization in the same widget as WidgetsApp, it complains:
```
The getter 'delegates' was called on null.
Receiver: null
Tried calling: delegates
```

```dart
  @override
  Widget build(BuildContext context) {
    return EasyLocalization(
      supportedLocales: [
        Locale('en', 'US'),
      ],
      fallbackLocale: Locale('en', 'US'),
      path: 'assets/i18n',
      saveLocale: false, // No shared preferences available in test context
      child: WidgetsApp(
        color: BottleColors.purple,
        onGenerateRoute: (settings) => MaterialPageRoute(
          settings: settings,
          builder: (_) => MediaQuery(
            data: device.mediaQueryData,
            child: WrapScreenUtil(
              Container(
                color: Color(0xFF84f06d),
                child: MediaQuery(
                  data: device.mediaQueryData
                      .copyWith(textScaleFactor: textScaleFactor),
                  child: widget,
                ),
              ),
            ),
          ),
        ),
        localizationsDelegates: EasyLocalization.of(context).delegates,
        supportedLocales: EasyLocalization.of(context).supportedLocales,
      ),
    );
  }
```

If I move up a level and insert the EasyLocalization widget inside the call to `pumpWidget` and wrap my app widget there, then it fails while building EasyLocalization:
```
[log] EasyLocalization
[log] initState
[log] easy localization: Build
[log] easy localization: Device locale en_US
[log] easy localization: Load asset from assets/i18n
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter_test/src/binding.dart': Failed assertion: line 1019 pos 24: '_phase ==
EnginePhase.flushSemantics ||
                       _phase == EnginePhase.sendSemanticsUpdate': is not true.

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1019:24)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#6      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#9      TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#10     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#11     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
#14     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#15     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
#16     TestHarnessUtils.pumpWidgetDevice (package:bottlepay/src/shared_widgets/test/util.dart:60:12)
#17     bottleMultiDeviceTest.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:bottlepay/src/shared_widgets/test/util.dart:154:28)
#18     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:921:22)
#21     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:919:26)
#22     WidgetTester.runAsync (package:flutter_test/src/widget_tester.dart:571:17)
#23     bottleMultiDeviceTest.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:bottlepay/src/shared_widgets/test/util.dart:153:26)
#24     bottleMultiDeviceTest.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:bottlepay/src/shared_widgets/test/util.dart:151:11)
#25     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
#38     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#39     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 35 frames from class _AssertionError, class _FakeAsync, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

What's the right way to initialize EasyLocalization during widget tests when there is no RunApp?

**Comment by acoutts** [comment]
If I modify `easy_localization_app.dart` to just return the child widget without returning the provider wrapped one, the unit test runs fine:
```dart
  @override
  Widget build(BuildContext context) {
    Widget returnWidget;
    log('easy localization: Build');
    return Container(
      color: widget.preloaderColor,
      child: StreamBuilder<Resource>(
          stream: bloc.outStream,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting &&
                !snapshot.hasData &&
                !snapshot.hasError) {
              returnWidget = EmptyPreloaderWidget();
            } else if (snapshot.hasData && !snapshot.hasError) {
              returnWidget = _EasyLocalizationProvider(
                widget,
                snapshot.data.locale,
                bloc: bloc,
                delegate: _EasyLocalizationDelegate(
                    translations: snapshot.data.translations,
                    supportedLocales: widget.supportedLocales),
              );
            } else if (snapshot.hasError) {
              returnWidget = FutureErrorWidget(msg: snapshot.error);
            }
            return widget.child; // Just return the child as a test
            return returnWidget;
          }),
    );
  }
```

**Comment by acoutts** [comment]
WOO got it!

Simple fix, just had to update my call to `pumpWidget` to set the phase to `EnginePhase.build` instead of the default `EnginePhase.sendSemanticsUpdate`.
