### ISSUE TITLE
Do not pass the context in new Flutter version 1.17.0 or above

### ISSUE THREAD

**Issue by pulstar** [aissat/easy_localization#186]
After upgrading Flutter to the new version (^1.17.0), do not pass the context to the methods el.tr() or el.plural(). It will crash the application, throwing the error below. I lost almost a week trying to figure out what was wrong.

```
E/flutter (15275): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (15275): At this point the state of the widget's element tree is no longer stable.
E/flutter (15275): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (15275): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
E/flutter (15275): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
E/flutter (15275): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
E/flutter (15275): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
E/flutter (15275): #4      Router.open (package:insignia_core/src/router.dart:25:28)
E/flutter (15275): #5      _SellerShopsMenuScreenState.build.<anonymous closure> (package:bargainer_pro/modules/seller/views/screens/shops/seller_shops_menu_screen.dart:118:18)
E/flutter (15275): #6      SelectionTile.build.<anonymous closure> (package:insignia_layout/src/selection_list.dart:67:20)
E/flutter (15275): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (15275): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (15275): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (15275): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (15275): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (15275): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (15275): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (15275): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (15275): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (15275): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (15275): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (15275): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (15275): #19     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (15275): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (15275): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (15275): #22     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (15275): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

**Comment by Overman775** [comment]
@pulstar i use to Flutter 1.17.0 and note have issues after updating.
1. Version Easy localization?
2. Please try run example Easy localization
3. Need code example to reproduce bug

**Comment by pulstar** [comment]
I updated Easy Localization to the last version but the problem still... Maybe I was passing the wrong context to the el.tr() method, but it worked fine when I removed the context I was passing to. What I don't understand is why this problem occurred only after upgrading Flutter, because I am using Easy Localization for over than a year without any problem.

**Comment by Overman775** [comment]
@pulstar to diagnose the error I need to see a sample code.

Try change el.tr() to

```dart
Text('title').tr() //Text widget
//or
'title'.tr(); //String
```

**Comment by pulstar** [comment]
Well, my app is working now... I just posted this to inform anyone that passing the wrong context to the el.tr() method will crash the app. Easy Localization is working fine and I love it. Thank you!
