### ISSUE TITLE
Source path empty

### ISSUE THREAD

**Issue by john916zhang** [aissat/easy_localization#224]
Version: 2.3.2

```
➜   flutter pub run easy_localization:generate
[ERROR] easy localization: Source path empty
```
It seemed that I should provide a source file name, so I did the following:

```
➜  flutter pub run easy_localization:generate --source-file test
Unhandled exception:
FormatException: Could not find an option named "source-file".
#0      Parser.validate (package:args/src/parser.dart:290:21)
#1      Parser.parseLongOption (package:args/src/parser.dart:279:7)
#2      Parser.parse (package:args/src/parser.dart:88:11)
#3      ArgParser.parse (package:args/src/arg_parser.dart:326:42)
#4      _generateOption (file:///Users/john/flutter/.pub-cache/hosted/pub.dartlang.org/easy_localization-2.3.2/bin/generate.dart:39:10)
#5      main (file:///Users/john/flutter/.pub-cache/hosted/pub.dartlang.org/easy_localization-2.3.2/bin/generate.dart:23:21)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

**Comment by Overman775** [comment]
run `flutter pub run easy_localization:generate -h` and recheck source folder and file

**Comment by john916zhang** [comment]
Since all the options have default values, it should not throw the error message to run `flutter pub run easy_localization:generate`. I upgraded to the 2.3.3, and the result is the same.

```
flutter pub run easy_localization:generate -h
-s, --source-dir     Folder containing localization files
                     (defaults to "resources/langs")
-O, --output-dir     Output folder stores for the generated file
                     (defaults to "lib/generated")
-o, --output-file    Output file name
                     (defaults to "codegen_loader.g.dart")
-f, --format         Support json or keys formats
                     [json (default), keys]
```
