### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by bnctth** [aissat/easy_localization#225]
When I try to hot reload, it results in an error:
```
I/flutter (28982): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28982): The following StateError was thrown building Container(bg: Color(0xffffffff)):
I/flutter (28982): Bad state: Stream has already been listened to.
I/flutter (28982): 
I/flutter (28982): The relevant error-causing widget was:
I/flutter (28982):   EasyLocalization file:///home/bnctth/dev/flutter/inventory/lib/main_app.dart:36:14
I/flutter (28982): 
I/flutter (28982): When the exception was thrown, this was the stack:
I/flutter (28982): #5      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:137:37)
I/flutter (28982): #6      _StreamBuilderBaseState.didUpdateWidget (package:flutter/src/widgets/async.dart:122:7)
I/flutter (28982): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4690:58)
I/flutter (28982): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
I/flutter (28982): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (28982): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28982): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
I/flutter (28982): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (28982): #16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
I/flutter (28982): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28982): #18     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
I/flutter (28982): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (28982): #21     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:387:11)
I/flutter (28982): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28982): #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
I/flutter (28982): #24     _InheritedProviderScopeElement.update (package:provider/src/inherited_provider.dart:407:11)
I/flutter (28982): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (28982): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28982): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
I/flutter (28982): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
I/flutter (28982): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
I/flutter (28982): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
I/flutter (28982): #32     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
I/flutter (28982): #33     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:96:11)
I/flutter (28982): #34     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)
I/flutter (28982): #35     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
I/flutter (28982): #36     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)
I/flutter (28982): #37     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:174:5)
I/flutter (28982): #38     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:244:5)
I/flutter (28982): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #43     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3225:13)
I/flutter (28982): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #45     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
I/flutter (28982): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #50     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
I/flutter (28982): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #58     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
I/flutter (28982): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #65     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1248:11)
I/flutter (28982): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #69     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:556:15)
I/flutter (28982): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)
I/flutter (28982): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
I/flutter (28982): #73     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
I/flutter (28982): #74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)
I/flutter (28982): #75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
I/flutter (28982): #76     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)
I/flutter (28982): #77     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
I/flutter (28982): #78     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
I/flutter (28982): #79     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
I/flutter (28982): #80     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
I/flutter (28982): #81     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:861:7)
I/flutter (28982): (elided 9 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (28982): 
I/flutter (28982): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

My main app widget:
```dart
class MyApp extends StatelessWidget {
  final GlobalKey<NavigatorState> navigatorKey;

  MyApp({this.navigatorKey});

  @override
  Widget build(BuildContext context) {
    FlutterError.onError = Crashlytics.instance.recordFlutterError;

    NetworkError.instance.init(navigatorKey);

    return MultiProvider(
      providers: [
        ChangeNotifierProvider<User>(
          create: (_) => User(),
        ),
        ChangeNotifierProvider<ProjectProvider>(
          create: (_) => ProjectProvider(),
        ),
      ],
      child: EasyLocalization(
        supportedLocales: [
          Locale('hu'),
          Locale('en', 'US'),
        ],
        fallbackLocale: Locale('en', 'US'),
        path: 'assets/translations',
        child: Builder(
          builder: (context) => MaterialApp(
            title: "title",
            navigatorKey: navigatorKey,
            localizationsDelegates: context.localizationDelegates,
            supportedLocales: context.supportedLocales,
            locale: context.locale,
            routes: <String, Widget Function(BuildContext)>{
              LoadingScreen.route: (context) => LoadingScreen(),
              Welcome.route: (context) => Welcome(),
              NoNetworkScreen.route: (context) => NoNetworkScreen(),
              MainScreen.route: (context) => MainScreen(),
              AddProjectScreen.route: (context) => AddProjectScreen(),
            },
          ),
        ),
      ),
    );
  }
}
```
Anywhere I use this library I use the .tr() method. If anything else is needed for the solution I am here to answer.

**Comment by Overman775** [comment]
@bnctth needs to bring up Eassy localization package, like in example

**Comment by Overman775** [comment]
@bnctth I am closing issue for lack of response. If you haven't fixed the problem, feel free to create a new one.
