### ISSUE TITLE
Error after hot reload

### ISSUE THREAD

**Issue by pulstar** [aissat/easy_localization#29]
I am getting the error below when I use the hot reload. It does not occur when I compile the app from the beggining at the first time.

E/flutter (23176): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(**No implementation found for method getAll on channel plugins.flutter.io/shared_preferences**)
E/flutter (23176): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (23176): <asynchronous suspension>
E/flutter (23176): #1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
E/flutter (23176): <asynchronous suspension>
E/flutter (23176): #2      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
E/flutter (23176): <asynchronous suspension>
E/flutter (23176): #3      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
E/flutter (23176): <asynchronous suspension>
E/flutter (23176): #4      _EasyLocalizationState.saveLocale (package:easy_localization/easy_localization_provider.dart:53:33)
E/flutter (23176): <asynchronous suspension>
E/flutter (23176): #5      _EasyLocalizationState.initState (package:easy_localization/easy_localization_provider.dart:36:5)
E/flutter (23176): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (23176): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (23176): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (23176): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (23176): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
E/flutter (23176): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
E/flutter (23176): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
E/flutter (23176): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter (23176): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
E/flutter (23176): #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
E/flutter (23176): #16     runApp (package:flutter/src/widgets/binding.dart:845:7)
E/flutter (23176): #17     main (package:bargainer_pro/main.dart:24:3)
E/flutter (23176): #18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter (23176): #19     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (23176): #20     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (23176): #21     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (23176): #22     runZoned (dart:async/zone.dart:1500:12)
E/flutter (23176): #23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter (23176): #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (23176): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by pulstar** [comment]
I found a solution adding the following line to the first line of the main() function:

SharedPreferences.setMockInitialValues({});
