### ISSUE TITLE
LateInitializationError: Field '_deviceLocale@1130168148' has not been initialized.

### ISSUE THREAD

**Issue by izzetemredemir** [aissat/easy_localization#353]
After Upgrading Flutter 2.0.1 I am facing this problem.

easy_localization version 3.0.0
```
I/flutter ( 5287): [🌎 Easy Localization] [DEBUG] Start
[  +35 ms] I/flutter ( 5287): [🌎 Easy Localization] [DEBUG] Init state
[  +99 ms] 
           ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
           The following LateError was thrown attaching to the render tree:
           LateInitializationError: Field '_deviceLocale@125168148' has not been initialized.
           
           When the exception was thrown, this was the stack:
           #0      EasyLocalizationController._deviceLocale (package:easy_localization/src/easy_localization_controller.dart)
           #1      new EasyLocalizationController.<anonymous closure> (package:easy_localization/src/easy_localization_controller.dart:52:48)
           #2      ListMixin.firstWhere (dart:collection/list.dart:161:15)
           #3      new EasyLocalizationController (package:easy_localization/src/easy_localization_controller.dart:51:34)
           #4      _EasyLocalizationState.initState (package:easy_localization/src/easy_localization_app.dart:120:30)
           #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)
           #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4469:5)
           #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
           #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
           #9      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1182:16)
           #10     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1153:5)
           #11     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1095:18)
           #12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2647:19)
           #13     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1094:13)
           #14     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:934:7)
           #15     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:7)
           (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

```
Flutter doctor output

[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)
```
    • Flutter version 2.0.1 at /home/..
    • Framework revision c5a4b4029c (23 hours ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/user/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /home/user/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

```

**Comment by izzetemredemir** [comment]
await EasyLocalization.ensureInitialized();

**Comment by theflutterfactory** [comment]
This thread shouldn't be closed.

await EasyLocalization.ensureInitialized(); 

is not a solution as it was also used prior to 3.0.0

**Comment by ImranR98** [comment]
This doesn't work when done in a background isolate.
