### ISSUE TITLE
Unhandled Exception: 'dart:ui/platform_dispatcher.dart'

### ISSUE THREAD

**Issue by BigGitWorld** [aissat/easy_localization#473]
Flutter: 2.8.0
Easy_localization: 3.0.0

The below error occurs when my  flutter app is started in raspberrypi:
Everything works correctly in my linux ubuntu system.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'dart:ui/platform_dispatcher.dart': Failed assertion: line 1530 pos 15: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:47:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      new Locale.fromSubtags (dart:ui/platform_dispatcher.dart:1530:15)
#3      StringToLocaleHelper.toLocale (package:easy_localization/src/utils.dart:44:23)
#4      EasyLocalizationController.initEasyLocation (package:easy_localization/src/easy_localization_controller.dart:123:42)
<asynchronous suspension>
#5      main (package:my_package/main.dart:24:3)
<asynchronous suspension>

```

main.dart:
```
void main() async { 
  ...
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  runApp(EasyLocalization(
    child: const ProviderScope(child: MyApp()),
    supportedLocales: const [
      Locale('en', "US")
    ],
    path: 'assets/translations',
    startLocale: const Locale('en', "US"),
    fallbackLocale: const Locale('en', "US"),
    saveLocale: true,
    useOnlyLangCode: true,
  ));
}
```

what is problem?

**Comment by BigGitWorld** [comment]
I found the problem.
I had changed the locale in ``raspi-config``, but the flutter could not specify it!.
