### ISSUE TITLE
type 'ParserRecovery' is not a subtype of type 'TypeBuilder?' in type cast

### ISSUE THREAD

**Issue by kabinswivt** [aissat/easy_localization#594]
``` dart
Unhandled exception:
Crash when compiling package:localala/src/localization/locale_keys.g.dart:
locale_keys.g.dart:1
type 'ParserRecovery' is not a subtype of type 'TypeBuilder?' in type cast

#0      OutlineBuilder._endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1962:37)
#1      OutlineBuilder.endClassMethod (package:front_end/src/fasta/source/outline_builder.dart:1836:5)
#2      Parser.parseMethod
parser_impl.dart:4888
#3      Parser.parseInvalidOperatorDeclaration
parser_impl.dart:9068
#4      Parser.recoverFromInvalidMember
parser_impl.dart:9116
#5      Parser.parseClassOrMixinOrExtensionOrEnumMemberImpl
parser_impl.dart:4545
#6      Parser.parseClassOrMixinOrExtensionBody
parser_impl.dart:4222

```

**Comment by Snofkin** [comment]
Please check if there is any empty string in your locale_keys.g.dart

**Comment by nitaking** [comment]
I experienced the same issue, Please check the following points:

- Words that can't be used as keys:
    - Reserved words:
        - `with`
        - `continue`
        - `try`
        
    - Symbols:
        - include `-`
        - `?`
- Duplicated keys
